package Insurance;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jzegarram
 */
public class InsuranceFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsuranceFrame
     */
    public InsuranceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInsurance = new javax.swing.ButtonGroup();
        jPanelNorth = new javax.swing.JPanel();
        jRadioButtonHousing = new javax.swing.JRadioButton();
        jRadioButtonMedicate = new javax.swing.JRadioButton();
        jPanelCenter = new javax.swing.JPanel();
        jPanelHousing = new javax.swing.JPanel();
        jPanelMedicate = new javax.swing.JPanel();
        jPanelSouth = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonHousing.setText("Housing");
        jPanelNorth.add(jRadioButtonHousing);

        jRadioButtonMedicate.setText("Medicate");
        jRadioButtonMedicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicateActionPerformed(evt);
            }
        });
        jPanelNorth.add(jRadioButtonMedicate);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.PAGE_START);

        jPanelCenter.setLayout(new java.awt.CardLayout());

        jPanelHousing.setLayout(new java.awt.CardLayout());
        jPanelCenter.add(jPanelHousing, "card2");

        jPanelMedicate.setLayout(new java.awt.CardLayout());
        jPanelCenter.add(jPanelMedicate, "card3");

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);
        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMedicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMedicateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInsurance;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelHousing;
    private javax.swing.JPanel jPanelMedicate;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JRadioButton jRadioButtonHousing;
    private javax.swing.JRadioButton jRadioButtonMedicate;
    // End of variables declaration//GEN-END:variables
}
